name: modeling
channels:
  - conda-forge
  - nodefaults
dependencies:
# python packages
  - python==3.9
  - pip
  - pandas
  - numpy
  - geopandas
  - ipykernel
  - statsmodels
# R packages
# pip installs
  - pip:
